name: Docs trigger

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  triggerdocswebsitebuild:
    runs-on: ubuntu-latest
    name: Trigger docs website build
    steps:

      - name: Generate token
        id: generate-token
        if: github.repository_owner == 'emteknetnz'
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner:
          repositories

      - name: Send API request
        shell: bash
        run: |
          # https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event
          RESP_CODE=$(curl -w %{http_code} -s -L -o /dev/null \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ steps.generate-token.outputs.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/emteknetnz/docs-test-w1/actions/workflows/docs-build/dispatches \
            -d '{}'
          )
          if [[ $RESP_CODE != "204" ]]; then
            echo "Failed to dispatch workflow - HTTP response code was $RESP_CODE"
            exit 1
          fi
